# Config file for the A-SOINN+ experiments

ALGORITHM: GDM

ALGORITHM_ARGS:  # TODO: GS parameter lists!
  MAX_AGE: 6000
  NUM_CONTEXT: 2
  LR_BMU: 0.5  # learning rate of BMU
  LR_sBMU: 0.005  # learning rate of second BMU
  A_THRESHOLD_GEM: 0.3  # activation threshold of G-EM network
  A_THRESHOLD_GSM: 0.03  # activation threshold of G-SM network
  SKIP_FRAMES: 2
  EPOCHS: 1  # 1 since continuous learning
  REPLAY: True
  SEMANTIC: True  # With G-SM layer
  INPUT_DIMENSION: 128  # Input dimension of the network


# Seed for category shuffling (TODO: Create a correct that fits runs)
SEED: 128

# Path to dataset (TODO: remove own directory)
# DS_PATH: /home/aleksej/phd/working_dir/LL/A_SOINN_plus/data/v_NICO_World_LL
DS_PATH: /home/aleksej/phd/working_dir/LL/A_SOINN_plus/data/v_NICO_World_LL_feature_vectors

# Path to feature extractor pkl file (null: do not use feature extraction)
# TODO: remove own dir
#FE_PATH: /home/aleksej/phd/working_dir/LL/A_SOINN_plus/data/feature_extractor
# FE_PATH:  /home/aleksej/phd/working_dir/LL/A_SOINN_plus/data/vNICORe100_feature_extractor_instance_128.h5
FE_PATH: null

# Which background complexity to train/test on
BC: B1

# Define which objects/instances to use for testing/training
# Note: o56,o57,o58,o59,o69 are removed to due permission issues
TEST_OBJECTS: [o8,o9,o18,o19,o28,o29,o38,o39,o48,o49,
               o55,o68,o78,o79,o88,o89,o98,o99]

TRAIN_OBJECTS: [o3,o4,o5,o6,o7,o13,o14,o15,o16,o17,o23,o24,o25,o26,o27,o33,
                o34,o35,o36,o37,o43,o44,o45,o46,o47,o53,o54,o55,
                o63,o64,o65,o66,o67,o73,o74,o75,o76,o77,o83,o84,o85,o86,
                o87,o93,o94,o95,o96,o97]
